### ISSUE TITLE
name 'bbox_iou' is not defined

### ISSUE THREAD

**Issue by marekjaszuk** [LiuShuai26/Mask-YOLOv3#2]
Hi,
While running the Mask-YOLO/myolo/test.py  I got the following error:
Mask-YOLO/myolo/utils.py", line 733, in decode_one_yolo_output
    if bbox_iou(boxes[index_i], boxes[index_j]) >= nms_threshold:
NameError: name 'bbox_iou' is not defined

I was searching for the bbox_iou function but I could not find one. Where can I take it from?

**Comment by LiuShuai26** [comment]
Hi,
This is not a complete project yet. And this project mostly refers to https://github.com/jianing-sun/Mask-YOLO/
I found bbox_iou function here: https://github.com/jianing-sun/Mask-YOLO/blob/f42d3470eb34bf5a967fe2016f342fea6827ea27/myolo/myolo_utils.py#L187
hope it will help you.
