### ISSUE TITLE
如何制作Mask-Yolo的数据集？

### ISSUE THREAD

**Issue by veraluoshu** [LiuShuai26/Mask-YOLOv3#3]
请问数据集格式是怎么样的，用labelImg还是labelme？期待回复！

**Comment by LiuShuai26** [comment]
给你提供一个制作数据集的网站。http://www.robots.ox.ac.uk/~vgg/software/via/

**Comment by LiuShuai26** [comment]
> 请问数据集格式是怎么样的，用labelImg还是labelme？期待回复！

给你提供一个制作数据集的网站。http://www.robots.ox.ac.uk/~vgg/software/via/
